site_name: Safas

theme: readthedocs
edit_uri: docs/
nav:
- Overview: 'index.md'
- Installation: 'installation.md'
- Use: 'use.md'
- Technical notes: 'technotes.md'
- Development: 'development.md'
- About:
   - 'License': 'about/license.md'
   - 'Notes': 'about/notes.md'
- FAQ: 'faq.md'
